Wind component with API connection finished
WildCodeSchool/2023-02-js-btz-spotcast pull request #4
Opened 2023-04-16 15:48 UTC by Ashitaaka

2023-04-16 15:51 UTC, Rom-Val approved these changes
Impeccable, on part donc sur le dashboard pour fetch.

2023-04-17 07:16 UTC, ldupas requested changes

2023-04-17 07:16 UTC, ldupas commented on src/components/widgets/wind/Wind.css
> +}
Pense à bien espacer ton css avec un saut à la ligne après une accolade fermante

2023-04-17 09:37 UTC, Rom-Val approved these changes

2023-04-17 10:33 UTC, ldupas approved these changes

2023-04-17 10:33 UTC, merged